puts "                  ****                  ****                 "
puts "            **          **         **           **           " 
puts "         **               **     **                **        "  
puts "       **                     **                     **      "      
puts "     **                                                **    "
puts "    **                                                  **   "
puts "    **                                                  **   "
puts "    **                  FILL MY HEART                   **   "
puts "     **                     WITH                       **    "
puts "       **                 SOME LOVE                  **      "
puts "         **                                        **        "
puts "            **                                  **           "
puts "                **                           **              "
puts "                    **                     **                "
puts "                        **             **                    " 
puts "                           **       **                       "
puts "                              **  **                         "
puts "                                **                           "